version: "3.9"

services:
  # vehicle-svc:
  #   build:
  #     context: ./apps/backend
  #     dockerfile: vehicle-svc/Dockerfile
  #   container_name: vehicle-svc
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_started
  #   environment:
  #     APP_ENV: docker
  #     APP_PORT: 50001
  #     MONGO_URI: mongodb://mongo:password@mongo:27017
  #     MONGO_DB: vehicle_db
  #     KAFKA_BROKERS: kafka:9092
  #   ports:
  #     - "50001:50001"
  #   networks:
  #     - qaas-network
  #   restart: unless-stopped

  # auth-svc:
  #   build:
  #     context: ./apps/backend
  #     dockerfile: auth-svc/Dockerfile
  #   container_name: auth-svc
  #   environment:
  #     APP_ENV: docker
  #     APP_PORT: 50000
  #   ports:
  #     - "50000:50000"
  #   networks:
  #     - qaas-network
  #   restart: unless-stopped
  # tracking-svc:
  #   build:
  #     context: ./apps/backend
  #     dockerfile: tracking-svc/Dockerfile
  #   container_name: tracking-svc
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_started
  #   environment:
  #     APP_ENV: docker
  #     APP_PORT: 50003
  #     MONGO_URI: mongodb://mongo:password@mongo:27017
  #     MONGO_DB: tracking_db
  #     KAFKA_BROKERS: kafka:9092
  #   ports:
  #     - "50003:50003"
  #   networks:
  #     - qaas-network
  #   restart: unless-stopped
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    networks:
      - qaas-workout
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - qaas-workout
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - qaas-workout

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - qaas-workout
volumes:
  mongodb_data:
  kafka_data:
networks:
  qaas-workout: